# Generated by Django 4.1.5 on 2023-02-10 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ChatBOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.FileField(default=None, max_length=250, null=True, upload_to='news/')),
                ('img2', models.FileField(default=None, max_length=250, null=True, upload_to='news/')),
                ('img3', models.FileField(default=None, max_length=250, null=True, upload_to='news/')),
                ('img4', models.FileField(default=None, max_length=250, null=True, upload_to='news/')),
            ],
        ),
        migrations.CreateModel(
            name='DataAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.FileField(default=None, max_length=250, null=True, upload_to='news1/')),
                ('img2', models.FileField(default=None, max_length=250, null=True, upload_to='news1/')),
                ('img3', models.FileField(default=None, max_length=250, null=True, upload_to='news1/')),
                ('img4', models.FileField(default=None, max_length=250, null=True, upload_to='news1/')),
            ],
        ),
        migrations.CreateModel(
            name='Hire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(max_length=70)),
                ('Requirement', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='IpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Comment', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(default=None, max_length=250, null=True, upload_to='news1/')),
            ],
        ),
        migrations.CreateModel(
            name='Web',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.FileField(default=None, max_length=250, null=True, upload_to='news/')),
                ('img2', models.FileField(default=None, max_length=250, null=True, upload_to='news/')),
                ('img3', models.FileField(default=None, max_length=250, null=True, upload_to='news/')),
                ('img4', models.FileField(default=None, max_length=250, null=True, upload_to='news/')),
                ('img5', models.FileField(default=None, max_length=250, null=True, upload_to='news/')),
                ('img6', models.FileField(default=None, max_length=250, null=True, upload_to='news/')),
                ('img7', models.FileField(default=None, max_length=250, null=True, upload_to='news/')),
                ('img8', models.FileField(default=None, max_length=250, null=True, upload_to='news/')),
            ],
        ),
        migrations.CreateModel(
            name='Lastnews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('news_desc', tinymce.models.HTMLField()),
                ('news_image', models.FileField(default=None, max_length=250, null=True, upload_to='news/')),
                ('news_image1', models.FileField(default=None, max_length=250, null=True, upload_to='news/')),
                ('news_image2', models.FileField(default=None, max_length=250, null=True, upload_to='news/')),
                ('video', models.FileField(default=None, max_length=250, null=True, upload_to='news/')),
                ('category', models.CharField(default='coding', max_length=150)),
                ('post_data', models.DateField(auto_now_add=True)),
                ('authors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='post_likes', to='home.ipmodel')),
            ],
        ),
    ]
